# Generated by Django 5.1.3 on 2024-11-13 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='electricity_cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вартість електроенергії (грн/кВт)'),
        ),
    ]
