# Generated by Django 5.1.3 on 2024-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_generalsettings_electricity_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='electricity_cost',
            field=models.FloatField(verbose_name='Вартість електроенергії (грн/кВт)'),
        ),
    ]
